import type { NichePageContent } from "@/content/niches/types"

const capturedAt = "2026-07-30"

export const lashArtistResearch: NichePageContent["research"] = {
  sources: [
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1bjukfz/does_your_lash_tech_have_a_booking_site/", capturedAt, publishedAt: "2024-03-21", sourceKind: "Lash artist community discussion", excerpt: "i have to follow, dm for availability, dm her a time and send a deposit and wait for a response.", theme: "DM bookings" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1bjukfz/does_your_lash_tech_have_a_booking_site/", capturedAt, publishedAt: "2024-03-21", sourceKind: "Lash artist reply", excerpt: "I need a booking system for my sanity. I can’t answer DMs all day.", theme: "DM bookings" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/17i9vd4/advice_on_no_shows/", capturedAt, publishedAt: "2023-10-28", sourceKind: "Lash artist community discussion", excerpt: "What do you do when you get a no show and they try book in again?", theme: "No-shows" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/17i9vd4/advice_on_no_shows/", capturedAt, publishedAt: "2023-10-28", sourceKind: "Lash artist reply", excerpt: "It’s your TIME and SKILLS getting paid so don’t waste it.", theme: "No-shows and payment" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1thva5k/how_many_no_showcancellations_have_you_ate_this/", capturedAt, publishedAt: "2026-05-19", sourceKind: "Lash artist community discussion", excerpt: "I’ve ate 3 no shows & over a dozen cancellations majority of which are happening day of.", theme: "No-shows" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1thva5k/how_many_no_showcancellations_have_you_ate_this/", capturedAt, publishedAt: "2026-05-19", sourceKind: "Lash artist reply", excerpt: "wasting prep time and blocked slots hurts income badly.", theme: "No-shows and earnings" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/17oowfh/lash_artist_client_software/", capturedAt, publishedAt: "2023-11-05", sourceKind: "Lash artist community discussion", excerpt: "What do other estheticians and lash artists use for a client book?", theme: "Losing track of client work" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/17oowfh/lash_artist_client_software/", capturedAt, publishedAt: "2023-11-05", sourceKind: "Lash artist reply", excerpt: "what curl, lengths and diameter I used and anything else I need to remember.", theme: "Losing track of client work" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1icm3qd/breaking_up_with_clients/", capturedAt, publishedAt: "2025-01-20", sourceKind: "Lash artist community discussion", excerpt: "clients are always messaging me or I’m editing photos and videos.", theme: "Losing track of the day" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1rj14z9/income_while_not_physically_lashing/", capturedAt, publishedAt: "2026-03-02", sourceKind: "Lash artist community discussion", excerpt: "We are the sole operators to generate revenue and if we are not, there is no money being made.", theme: "Earnings visibility" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/18yg17a/question_about_cost_of_lashes_for_techs/", capturedAt, publishedAt: "2024-01-04", sourceKind: "Client and lash-tech community discussion", excerpt: "she will include the cost of the brown lashes in her expenses.", theme: "Expenses" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/v4pniw/independent_lash_tech_salary/", capturedAt, publishedAt: "2022-06-04", sourceKind: "Independent lash-tech discussion", excerpt: "after your expenses about how much do you make each year (or monthly, weekly, daily)", theme: "Earnings visibility" },
    { sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/10nw0wl/how_often_do_lash_techs_restock_on_their_supplies/", capturedAt, publishedAt: "2023-01-29", sourceKind: "Lash-tech supplies discussion", excerpt: "how many clients you get as a lash tech per week, how much are your expenses", theme: "Earnings visibility" },
    { sourceUrl: "https://www.reddit.com/r/lashextensions/comments/1v8ym18/how_to_prevent_late_clients_without_driving_me/", capturedAt, publishedAt: "2026-07-28", sourceKind: "Lash-client and artist community discussion", excerpt: "I’m not going to push back my other clients because other people are late.", theme: "Losing track of the day" },
    { sourceUrl: "https://www.reddit.com/r/lashextensions/comments/1plvmx7/client_walks_in_to_book_sameday_appointment_and/", capturedAt, publishedAt: "2025-12-21", sourceKind: "Lash-client community discussion", excerpt: "I also moved away from DM bookings completely.", theme: "DM bookings" },
  ],
  verbatims: [
    { phrase: "i have to follow, dm for availability, dm her a time and send a deposit and wait for a response.", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1bjukfz/does_your_lash_tech_have_a_booking_site/", theme: "DM bookings" },
    { phrase: "I need a booking system for my sanity. I can’t answer DMs all day.", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1bjukfz/does_your_lash_tech_have_a_booking_site/", theme: "DM bookings" },
    { phrase: "What do you do when you get a no show and they try book in again?", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/17i9vd4/advice_on_no_shows/", theme: "No-shows" },
    { phrase: "I’m starting out my business and I’m feeling guilty being firm.", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/17i9vd4/advice_on_no_shows/", theme: "No-shows" },
    { phrase: "It’s your TIME and SKILLS getting paid so don’t waste it.", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/17i9vd4/advice_on_no_shows/", theme: "No-shows and payment" },
    { phrase: "I’ve ate 3 no shows & over a dozen cancellations majority of which are happening day of.", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1thva5k/how_many_no_showcancellations_have_you_ate_this/", theme: "No-shows" },
    { phrase: "wasting prep time and blocked slots hurts income badly.", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1thva5k/how_many_no_showcancellations_have_you_ate_this/", theme: "No-shows and earnings" },
    { phrase: "What do other estheticians and lash artists use for a client book?", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/17oowfh/lash_artist_client_software/", theme: "Losing track of client work" },
    { phrase: "what curl, lengths and diameter I used and anything else I need to remember.", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/17oowfh/lash_artist_client_software/", theme: "Losing track of client work" },
    { phrase: "I never truly have a day off, clients are always messaging me.", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1icm3qd/breaking_up_with_clients/", theme: "Losing track of the day" },
    { phrase: "We are the sole operators to generate revenue and if we are not, there is no money being made.", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/1rj14z9/income_while_not_physically_lashing/", theme: "Earnings visibility" },
    { phrase: "she will include the cost of the brown lashes in her expenses.", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/18yg17a/question_about_cost_of_lashes_for_techs/", theme: "Expenses" },
    { phrase: "after your expenses about how much do you make each year (or monthly, weekly, daily)", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/v4pniw/independent_lash_tech_salary/", theme: "Earnings visibility" },
    { phrase: "how many clients you get as a lash tech per week, how much are your expenses", sourceUrl: "https://www.reddit.com/r/eyelashextensions/comments/10nw0wl/how_often_do_lash_techs_restock_on_their_supplies/", theme: "Earnings visibility" },
    { phrase: "I’m not going to push back my other clients because other people are late.", sourceUrl: "https://www.reddit.com/r/lashextensions/comments/1v8ym18/how_to_prevent_late_clients_without_driving_me/", theme: "Losing track of the day" },
  ],
}
